#!/bin/bash

# let's start fresh
rm -rf .demeteorized
rm /tmp/newfile

# run + cd
demeteorizer
cd .demeteorized

# sed hacks
sed 's/"mongodb": "1.3.7-meteor"/"mongodb": "1.3.12"/' package.json >> /tmp/newfile
cp /tmp/newfile package.json

# deploy + go back to project dir
modulus deploy -p assistant
cd ..
